import { COMPANY_NAME } from 'constants';
import React from 'react';
import AppBar from 'components/AppBar';
import Container from 'components/Container';
import '../artical.less';
//资费标准信息页面
export default class Standard extends React.Component {
    render() {
        return (
            <Container>
                <AppBar title="本平台资费标准" backward fixed/>
                <div className="artical-doc">
                    <div>
                        <h2>《资费标准》</h2>
                        <p>用户通过本平台参与期货交易合作将涉及交易综合费和履约保证金的发生。 </p>
                        <h3>一、交易综合费</h3>
                        <p className="text-indent">
                            1、交易综合费为本平台向用户收取的费用。交易综合费包含：1）本平台为用户提供交易合作信息发布、交易合作撮合、交易指令通讯、交易风控管理与交易清结算等服务而收取的信息服务费；2）本平台代投资人收取用于补偿投资人帐户交易过程中产生的手续费；3）本平台收取用于为用户提供资金存取、冻结、解冻和支付等服务手续费。</p>
                        <h3>2、交易综合费标准：</h3>
                        <table>
                            <tbody>
                            <tr>
                                <th>品种</th>
                                <th>交易综合费</th>
                            </tr>
                            <tr>
                                <td>沪金</td>
                                <td>35元/手</td>
                            </tr>
                            <tr>
                                <td>沪银</td>
                                <td>19元/手</td>
                            </tr>
                            <tr>
                                <td>沪镍</td>
                                <td>29元/手</td>
                            </tr>
                            <tr>
                                <td>沪铜</td>
                                <td>40元/手</td>
                            </tr>
                            <tr>
                                <td>螺纹钢</td>
                                <td>15元/手</td>
                            </tr>
                            <tr>
                                <td>天然橡胶</td>
                                <td>40元/手</td>
                            </tr>
                            <tr>
                                <td>白糖</td>
                                <td>15元/手</td>
                            </tr>
                            <tr>
                                <td>聚丙烯</td>
                                <td>30元/手</td>
                            </tr>
                            <tr>
                                <td>美原油</td>
                                <td>20美元/手</td>
                            </tr>
                            <tr>
                                <td>美黄金</td>
                                <td>20美元/手</td>
                            </tr>
                            <tr>
                                <td>恒指</td>
                                <td>150港币/手</td>
                            </tr>
                            <tr>
                                <td>小恒指</td>
                                <td>100港币/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">3、交易综合费于用户签署《交易合作协议》时即支付。交易综合费一经支付不予退还。 </p>
                        <h3>二、履约保证金</h3>
                        <p className="text-indent">1、履约保证金为用户委托本平台系统冻结用于履行交易亏损赔付义务的保证金。</p>
                        <p className="text-indent">2、沪金履约保证金按用户所选择的止损金额，每手冻结250元~3100元履约保证金。</p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>150元/手</td>
                                <td>250元/手</td>
                            </tr>
                            <tr>
                                <td>200元/手</td>
                                <td>300元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>600元/手</td>
                            </tr>
                            <tr>
                                <td>1,000元/手</td>
                                <td>1,100元/手</td>
                            </tr>
                            <tr>
                                <td>2,000元/手</td>
                                <td>2,100元/手</td>
                            </tr>
                            <tr>
                                <td>3,000元/手</td>
                                <td>3,100元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            3、沪银履约保证金按用户所选择的止损金额，每手冻结75元~1080元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>45元/手</td>
                                <td>75元/手</td>
                            </tr>
                            <tr>
                                <td>75元/手</td>
                                <td>105元/手</td>
                            </tr>
                            <tr>
                                <td>150元/手</td>
                                <td>180元/手</td>
                            </tr>
                            <tr>
                                <td>300元/手</td>
                                <td>330元/手</td>
                            </tr>
                            <tr>
                                <td>600元/手</td>
                                <td>630元/手</td>
                            </tr>
                            <tr>
                                <td>1050元/手</td>
                                <td>1080元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            4、沪镍履约保证金按用户所选择的止损金额，每手冻结110元~1040元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>70元/手</td>
                                <td>110元/手</td>
                            </tr>
                            <tr>
                                <td>150元/手</td>
                                <td>190元/手</td>
                            </tr>
                            <tr>
                                <td>300元/手</td>
                                <td>340元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>540元/手</td>
                            </tr>
                            <tr>
                                <td>800元/手</td>
                                <td>840元/手</td>
                            </tr>
                            <tr>
                                <td>1000元/手</td>
                                <td>1040元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            5、沪铜履约保证金按用户所选择的止损金额，每手冻结350元~5100元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>250元/手</td>
                                <td>350元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>600元/手</td>
                            </tr>
                            <tr>
                                <td>1000元/手</td>
                                <td>1100元/手</td>
                            </tr>
                            <tr>
                                <td>2000元/手</td>
                                <td>2100元/手</td>
                            </tr>
                            <tr>
                                <td>3000元/手</td>
                                <td>3100元/手</td>
                            </tr>
                            <tr>
                                <td>5000元/手</td>
                                <td>5100元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            6、螺纹钢履约保证金按用户所选择的止损金额，每手冻结50元~520元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>30元/手</td>
                                <td>50元/手</td>
                            </tr>
                            <tr>
                                <td>50元/手</td>
                                <td>70元/手</td>
                            </tr>
                            <tr>
                                <td>100元/手</td>
                                <td>120元/手</td>
                            </tr>
                            <tr>
                                <td>300元/手</td>
                                <td>320元/手</td>
                            </tr>
                            <tr>
                                <td>400元/手</td>
                                <td>420元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>520元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            7、天然橡胶履约保证金按用户所选择的止损金额，每手冻结350元~5100元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>250元/手</td>
                                <td>350元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>600元/手</td>
                            </tr>
                            <tr>
                                <td>1000元/手</td>
                                <td>1100元/手</td>
                            </tr>
                            <tr>
                                <td>2000元/手</td>
                                <td>2100元/手</td>
                            </tr>
                            <tr>
                                <td>3000元/手</td>
                                <td>3100元/手</td>
                            </tr>
                            <tr>
                                <td>5000元/手</td>
                                <td>5100元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            8、白糖履约保证金按用户所选择的止损金额，每手冻结70元~1020元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>50元/手</td>
                                <td>70元/手</td>
                            </tr>
                            <tr>
                                <td>100元/手</td>
                                <td>120元/手</td>
                            </tr>
                            <tr>
                                <td>200元/手</td>
                                <td>220元/手</td>
                            </tr>
                            <tr>
                                <td>300元/手</td>
                                <td>320元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>520元/手</td>
                            </tr>
                            <tr>
                                <td>1000元/手</td>
                                <td>1020元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            9、聚丙烯履约保证金按用户所选择的止损金额，每手冻结60元~510元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>50元/手</td>
                                <td>60元/手</td>
                            </tr>
                            <tr>
                                <td>100元/手</td>
                                <td>110元/手</td>
                            </tr>
                            <tr>
                                <td>200元/手</td>
                                <td>210元/手</td>
                            </tr>
                            <tr>
                                <td>300元/手</td>
                                <td>310元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>510元/手</td>
                            </tr>
                            <tr>
                                <td>500元/手</td>
                                <td>510元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            10、小恒指履约保证金按用户所选择的止损金额，每手冻结140港币~2040港币履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>100港币/手</td>
                                <td>140港币/手</td>
                            </tr>
                            <tr>
                                <td>300港币/手</td>
                                <td>340港币/手</td>
                            </tr>
                            <tr>
                                <td>500港币/手</td>
                                <td>540港币/手</td>
                            </tr>
                            <tr>
                                <td>800港币/手</td>
                                <td>840港币/手</td>
                            </tr>
                            <tr>
                                <td>1000港币/手</td>
                                <td>1040港币/手</td>
                            </tr>
                            <tr>
                                <td>2000港币/手</td>
                                <td>2040港币/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            11、恒指履约保证金按用户所选择的止损金额，每手冻结700港币~5200港币履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>500港币/手</td>
                                <td>700港币/手</td>
                            </tr>
                            <tr>
                                <td>1000港币/手</td>
                                <td>1200港币/手</td>
                            </tr>
                            <tr>
                                <td>1500港币/手</td>
                                <td>1700港币/手</td>
                            </tr>
                            <tr>
                                <td>2000港币/手</td>
                                <td>2200港币/手</td>
                            </tr>
                            <tr>
                                <td>2500港币/手</td>
                                <td>2700港币/手</td>
                            </tr>
                            <tr>
                                <td>5000港币/手</td>
                                <td>5200港币/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            12、美原油履约保证金按用户所选择的止损金额，每手冻结100美元~1050美元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>50美元/手</td>
                                <td>100美元/手</td>
                            </tr>
                            <tr>
                                <td>100美元/手</td>
                                <td>150美元/手</td>
                            </tr>
                            <tr>
                                <td>200美元/手</td>
                                <td>250美元/手</td>
                            </tr>
                            <tr>
                                <td>500美元/手</td>
                                <td>550美元/手</td>
                            </tr>
                            <tr>
                                <td>800美元/手</td>
                                <td>850美元/手</td>
                            </tr>
                            <tr>
                                <td>1000美元/手</td>
                                <td>1050美元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            13、美黄金履约保证金按用户所选择的止损金额，每手冻结100美元~1050美元履约保证金。
                        </p>
                        <table>
                            <tbody>
                            <tr>
                                <th>触发止损额</th>
                                <th>冻结履约保证金</th>
                            </tr>
                            <tr>
                                <td>50美元/手</td>
                                <td>100美元/手</td>
                            </tr>
                            <tr>
                                <td>100美元/手</td>
                                <td>150美元/手</td>
                            </tr>
                            <tr>
                                <td>200美元/手</td>
                                <td>250美元/手</td>
                            </tr>
                            <tr>
                                <td>500美元/手</td>
                                <td>550美元/手</td>
                            </tr>
                            <tr>
                                <td>800美元/手</td>
                                <td>850美元/手</td>
                            </tr>
                            <tr>
                                <td>1000美元/手</td>
                                <td>1050美元/手</td>
                            </tr>
                            </tbody>
                        </table>
                        <p className="text-indent">
                            14、交易合作结束，根据本平台清结算结果，如交易盈利，用户冻结履约保证金全额解冻。如交易亏损，本平台从用户冻结履约保证金中，扣减用户所应承担亏损赔付额的数额，扣减后余额解冻
                        </p>
                        <p className="red">如交易亏损大于用户冻结履约保证金，则超过的亏损部分由用户自行承担。</p>
                        <p>本附件系用户与投资人签署《交易合作协议》的重要组成部分，具有同等法律效力。</p>
                    </div>
                </div>
            </Container>
        )
    }
}
